project/app/models.py
from app import db, login_manager
from flask_login import UserMixin

class User(db.Model, UserMixin):
    id = db.Column(db.String, primary_key=True)
    email = db.Column(db.String(100), unique=True, nullable=False)
    name = db.Column(db.String(100), nullable=False)


    def __repr__(self):
        return f"<User {self.name}>"

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(str(user_id))

project/app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_oauthlib.client import OAuth
from config import Config

db = SQLAlchemy()
login_manager = LoginManager()
oauth = OAuth()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    app.config["SECRET_KEY"] = Config.SECRET_KEY

    db.init_app(app)
    login_manager.init_app(app)
    oauth.init_app(app)

    with app.app_context():
        db.create_all()  # Create database tables within the app context

    from app.routes import main
    app.register_blueprint(main)

    return app

project/app/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, jsonify, session
from app import oauth, db,models, login_manager,books,movie,artworks
from flask_login import LoginManager, UserMixin, login_user, logout_user, login_required, current_user
from config import Config

main = Blueprint("main", __name__)

google = oauth.remote_app(
    "google",
    consumer_key=Config.GOOGLE_OAUTH_CLIENT_ID,
    consumer_secret=Config.GOOGLE_OAUTH_CLIENT_SECRET,
    request_token_params={"scope": "email profile"},
    base_url="https://www.googleapis.com/oauth2/v1/",
    request_token_url=None,
    access_token_method="POST",
    access_token_url="https://accounts.google.com/o/oauth2/token",
    authorize_url="https://accounts.google.com/o/oauth2/auth",
)

login_manager = LoginManager()
login_manager.login_view = 'main.login'


def load_user(user_id):
    return models.User.query.get(str(user_id))

@main.route("/")
def index():
    
    if current_user.is_authenticated:
        return render_template("index.html", user=current_user)
    else:
        return render_template("index.html")



@main.route("/login")
def login():
    callback = url_for("main.authorized", _external=True, _scheme="http")
    return google.authorize(callback=callback)


@main.route("/logout")
@login_required
def logout():
    logout_user()  
    session.pop("google_token", None)
    session.pop("user", None)
    return redirect(url_for(".index"))


@main.route("/authorized")
def authorized():
    resp = google.authorized_response()
    if resp is None or resp.get('access_token') is None:
        flash("Authorization failed.")
        return redirect(url_for(".index"))

    access_token = resp["access_token"]
    session['google_token'] = (access_token, '')

    # Get user information
    user_data = google.get("https://www.googleapis.com/oauth2/v1/userinfo")
    if not user_data.status == 200:
        flash("Failed to fetch user data.")
        return redirect(url_for(".index"))

    
    user_id = user_data.data["id"]
    user_email = user_data.data["email"]
    user_name = user_data.data["name"]

# Check if the user already exists in the database
    user = models.User.query.get(user_id)

# If the user does not exist, create a new User object and add it to the database
    if user is None:
        user = models.User(id=user_id, email=user_email, name=user_name)
        db.session.add(user)
        db.session.commit()

# Log in the user
    login_user(user, remember=True)


    flash(f"You were successfully logged in as {user_data.data['name']}.")
    return redirect(url_for(".index"))

@main.route("/book_to_movie", methods=["GET", "POST"])
def book_to_movie():
    if current_user.is_authenticated:
        if request.method == "POST":
            book = request.form.get("book")
            if book:
                book_data = books.get_book(book,Config.GOOGLE_BOOK_API_KEY)
                movie_data = movie.get_movie(book,Config.TMDB_API_KEY)
                artwork_data = artworks.artwork()
                return render_template("book_to_movie.html", book_data=book_data, movie_data=movie_data,artwork_data = artwork_data)
            else:
                flash("Book name is required.")
                return render_template("book_to_movie.html")
    else:
        flash("Please log in to access the book_to_movie recommendation system.")
        return redirect(url_for('main.index'))
            



@google.tokengetter
def get_google_oauth_token():
    return session.get('google_token')

project/app/templates/book_to_movie.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Artwork Generator</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">

<body>
    <header>
        <h1>Movie to Artwork Recommendation Generator</h1>
        <a href="{{ url_for('main.index') }}">Home</a>
    </header>
    <div class="main">
        <div class="main-content">
            <form method="post" action="{{ url_for('main.book_to_movie') }}">
                <div class="form-box">
                    <div style="display: flex;align-items: center;height: 80px;">
                        <label for="book">Movie Name:</label>
                        <input type="text" name="book" id="book" required>
                    </div>
                    <button type="submit">Generate Recommendation </button>
                </div>
            </form>

           <div class="bottom-content" >
               {% if movie_data %}
            <div style="display: flex;flex-direction: column;">
                <h2>Movie</h2>
                <div class="item-box">
                    <ul>
                    <li><strong>Title:</strong> {{ movie_data.title}}</li>
                    <li><strong>Overview:</strong> {{ movie_data.overview }}</li>
                    <li><strong>Date:</strong> {{ movie_data.release_date}}</li>
                    <li><strong>Rating:</strong> {{ movie_data.vote_average}}</li>
                    </ul>
                </div>
            </div>
               {% endif %}
               {% if artwork_data %}
            <div style="display: flex; flex-direction: column;">
                <h2 style="margin-right: 65px;">Artwork</h2>
                <div class="item-box">
                    <ul>
                        <li><strong>Title:</strong> {{ artwork_data['title'] }}</li>
                    <li><strong>Year:</strong> {{ artwork_data['accessionYear'] }}</li>
                    </ul>
                     <img src="{{ artwork_data['primaryImage'] }}" alt="artwork image" />
                </div>
            </div>
               {% endif %}
           </div>
        </div>


    </div>
</body>
<style>
    /* Additional inline styles for a fancier look */
    /* CSS styling for the document */
    * {
        margin: 0;
        padding: 0;
    }

    body {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        /* background-color: rgb(16,27,56,0.9); */
        background-color: rgb(7, 24, 59);
        margin: 1;
        padding: 0;
    }

    header {
        display: flex;
        justify-content: space-around;
        padding: 20px;
        align-items: center;
        background-color: rgba(5, 55, 110);

        color: white;
        text-align: center;
        padding: 20px 0;
        height: 100px;
        box-sizing: border-box;
    }

    header a {
        display: inline-block;
        width: 84px;
        height: 36px;
        border: 1px solid #dedede;
        border-radius: 26px;
        line-height: 36px;
        text-align: center;

    }

    header h1 {
        font-size: 40px;
        margin: 1;
        text-transform: uppercase;
    }

    header a {
        color: #fff;
        text-decoration: none;
        margin-left: 10px;
        font-weight: bold;
    }

    .main {
        display: flex;
        justify-content: center;
        align-items: center;
        width: 1200px;
        height: calc(100vh - 200px);
        box-sizing: border-box;
        margin: 20px auto;
        padding: 20px;
        background-color: rgb(5, 55, 110);
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
    }

    .main-content {
        display: flex;
        flex-direction: column;
        width: 1200px;
        height: 700px;

    }
.bottom-content{
    padding: 60px;
    box-sizing: border-box;
    width: 100%;
    display: flex;
    justify-content: space-around;
}
    form {
        margin-bottom: 15px;
        display: flex;
        flex-direction: column;
        justify-content: center;
    }

    label {
        width: 200px;
        display: inline-block;
        color: #fff;
        font-weight: bold;
        display: block;
        margin-bottom: 16px;
        font-size: 20px;
        margin-left: 86px;
    }

    input[type="text"] {
        /* width: calc(100% - 22px); */
        width: 400px;
        padding: 10px;
        margin-bottom: 15px;
        border: 2px solid #ccc;
        border-radius: 4px;
        font-size: 20px;
    }

    button[type="submit"] {
        width: 300px;
        height: 50px;
        background-color: rgb(5 93 135);
        color: white;
        padding: 12px 24px;
        border: none;
        border-radius: 30px;
        cursor: pointer;
        font-size: 20px;
        margin-left: 80px;
        margin-top: 8px;
    }

    .item-box {
        width: 460px;
        /* border: 1px solid #fff; */
        padding: 20px;
        padding-top: 0;
        /* margin-top: 20px; */
        border-radius: 8px;
        color: black;
    }
ul li{
    line-height: 42px;
}
    .item-box p {
        color: #fff;
    }

    h2 {
        font-size: 24px;
        margin-top: 19px;
        color: #fff;
        margin-right: 90px;

    }

    p {
        font-size: 18px;
        line-height: 1.5;
        color: #555;
    }

    img {
        display: block;
        margin: 0 auto;
        max-width: 100%;
        height: auto;
    }
    .form-box{
        display: flex;
    }
</style>
</head>

</html>

project/app/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Book to Movie Recommendation System</title>
    <body>
  {% if user %}

      <div class="header">
        <h2>{{ user.name }}</h2>
        <p><a href="{{ url_for('main.logout') }}">Logout</a></p>
      </div>
  {% else %}
            <h1>Artwork Recommendation</h1>
            <p></p>

            <div class="recommendation">
              <h2>Starry Night</h2>
              <p>Painting by Vincent Van Gogh</p>
              <p>
                Immerse yourself in the swirling, expressive skies over the
                quiet village in Vincent Van Gogh's iconic painting "Starry
                Night."
              </p>
              <h4>Rating:</h4>
              <img src="{{ url_for('static', filename='src/star.png') }}" /><img src="{{ url_for('static', filename='src/star.png') }}" /><img src="{{ url_for('static', filename='src/star.png') }}"/>
              <div class="img-box">
                <img src="{{ url_for('static', filename='src/top.jpg') }}" />
              </div>
            </div>

            <div class="recommendation">
              <h2>The Birth of Venus</h2>
              <p>Painting by Sandro Botticelli</p>
              <p>Movie directed by Baz Luhrmann</p>
              <p>
                Marvel at the beauty of the goddess Venus emerging from the sea
                in Sandro Botticelli's timeless Renaissance masterpiece "The
                Birth of Venus."
              </p>
              <h4>Rating:</h4>
              <img src="{{ url_for('static', filename='src/star.png') }}" /><img src="{{ url_for('static', filename='src/star.png') }}" /><img
                src="{{ url_for('static', filename='src/star.png') }}"
              />
              <div class="img-box">
                <img src="{{ url_for('static', filename='src/bottom.png') }}" />
              </div>
            </div>
          <p class="login-link">
            Please <a href="{{ url_for('main.login') }}">login</a> to access the
            system
          </p>
  {% endif %}
  {% if user %}
          <div class="container input-container">
            <h2>Movie Recommendation</h2>
            <form action="{{ url_for('main.book_to_movie') }}" method="POST">
              <label for="bookName" style="color: #fff;"
                >Please Enter Your Name:</label
              >
              <input type="text" id="bookName" name="bookName" required />
              <button type="submit">Generate Recommendation</button>
            </form>
          </div>

  {% endif %}
    </body>
    <style>
      /* Add your CSS styling here */
      * {
        margin: 0;
        padding: 0;
      }
      body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: rgb(7, 24, 59);
      }
      .header {
        width: 100%;
        height: 80px;

        background-color: rgba(5, 55, 110);
        padding: 0 200px;
        box-sizing: border-box;
        display: flex;
        justify-content: space-between;
        align-items: center;
      }
      .header h2 {
        color: #fff;
      }
      .header p {
        width: 100px;
        height: 40px;
        color: #fff;
        line-height: 40px;
        border: 1px solid #fff;
        border-radius: 36px;
      }
      .header a {
        color: #fff;
      }
      .out-box {
        padding: 0 130px;
        box-sizing: border-box;
        display: flex;
        justify-content: space-around;
      }
      .content-box-right {
        margin-top: 30px;
        padding-bottom: 30px;
        box-sizing: border-box;
        box-sizing: border-box;
        width: 40%;
        height: calc(100vh - 90px);
        overflow-y: auto;
      }
      .content-box-right::-webkit-scrollbar {
        width: 8px;
        height: 10px;
      }
      .content-box-right::-webkit-scrollbar-thumb {
        background: #ccc;
        border-radius: 5px;
      }
      .content-box-left {
        width: 40%;
        height: 300px;
        background-color: rgba(5, 55, 110);
        margin-top: 30px;
        border-radius: 10px;
      }
      .container {
        max-width: 800px;
        margin: 0 auto;
        padding: 20px;
        background-color: rgb(5, 55, 110);
        border-radius: 8px;
      }

      h1 {
        text-align: center;
        color: #fff;
        font-size: 36px;
        margin-bottom: 20px;
      }

      p {
        text-align: center;
        color: #fff;
        font-size: 18px;
      }

      .recommendation {
        margin-top: 40px;
        padding: 20px;
        border-radius: 8px;
      }

      h2 {
        color: #fff;
        font-size: 24px;
        margin-bottom: 10px;
      }

      .recommendation p {
        color: #666;
        font-size: 18px;
        margin-bottom: 15px;
        text-align: left;
        line-height: 26px;
      }

      .recommendation:last-child {
        margin-bottom: 0;
      }

      a {
        color: #ff6f61;
        text-decoration: none;
        font-weight: bold;
      }

      .login-link {
        text-align: center;
        margin-top: 20px;
        font-size: 18px;
      }

      .login-link a {
        /* background-color: rgb(5 93 135); */
        color: rgb(5 93 135);
      }

      .input-container {
        text-align: center;
        margin-top: 20px;
      }

      label {
        font-size: 18px;
        font-weight: bold;
        display: block;
        margin-bottom: 10px;
        color: #333;
      }

      input[type="text"] {
        width: 90%;
        padding: 10px;
        margin-bottom: 20px;
        border: 2px solid #ccc;
        border-radius: 4px;
        font-size: 16px;
      }

      button[type="submit"] {
        background-color: rgb(5 93 135);
        color: white;
        padding: 12px 24px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 18px;
        border-radius: 30px;
      }
      /* ===== */
      .star {
        /* margin: 200px auto 0; */
        position: relative;
        width: 0px;
        height: 0px;
        border-color: yellow transparent transparent transparent;
        border-width: 41.41px 57.06px;
        border-style: solid;
      }

      .star::before {
        content: "";
        display: block;
        position: absolute;
        left: -57.06px;
        top: -41.41px;
        border-color: yellow transparent transparent transparent;
        border-width: 41.41px 57.06px;
        border-style: solid;
        transform: rotate(72deg);
        transform-origin: 50% 22.5%;
      }

      .star::after {
        content: "";
        display: block;
        position: absolute;
        left: -57.06px;
        top: -41.41px;
        border-color: yellow transparent transparent transparent;
        border-width: 41.41px 57.06px;
        border-style: solid;
        transform: rotate(-72deg);
        transform-origin: 50% 22.5%;
      }
      img {
        width: 22px;
        height: 22px;
        vertical-align: middle;
        margin-left: 10px;
        /* margin-top: 10px; */
      }
      h4 {
        display: inline-block;
        vertical-align: middle;
        color: #fff;
      }
      .img-box {
        width: 100%;
        height: 300px;
        display: flex;
        justify-content: center;
      }
      .img-box img {
        width: 300px;
        height: 300px;
        margin-top: 10px;
      }
    </style>
  </head>
</html>